[project]
name = "fdi-sbc-g01"
version = "0.1.0"
description = "Proyecto para gestionar un sistema de bases de conocimiento."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.7",
    "black>=23.9.1",
]