[project]
name = "fdi-sbc-g01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=24.10.0",
    "click>=8.1.7",
    "ollama>=0.4.2",
]
